name: Android CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run Unit tests
        run: bash ./FinancialChecker/gradlew test --stacktrace 

  build:
    name: Build Project
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build debug APK
        run: bash ./FinancialChecker/gradlew assembleDebug --stacktrace
      - name: Create APK artifact
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: FinancialChecker/app/build/outputs/apk/debug/app-debug.apk
