name: Android CI
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    types: [ opened, edited ]
    branches: [ '*' ]

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Run Unit tests
        run: bash ./gradlew test --stacktrace 

  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
        
      - name: Create APK artifact
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
