name: Android CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'
          
      - name: Run Unit tests
        run: bash ./gradlew test --stacktrace 

  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'
          
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace

      - name: Get git hash
        shell: bash
        run: |
            echo ${{ github.sha }}
            echo "GITHUB_SHA=${{ github.sha }}" >> $GITHUB_ENV
            echo "GITHUB_SHA_7=${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - name: Rename generated APK
        shell: bash
        run: |
            cd ./app/build/outputs/apk/debug/
            mv *.apk FinancialChecker-${{ env.GITHUB_SHA_7 }}.apk
        
      - name: Create APK artifact
        uses: actions/upload-artifact@v1
        with:
          name: FinancialChecker-${{ env.GITHUB_SHA_7 }}
          path: ./app/build/outputs/apk/debug/FinancialChecker-${{ env.GITHUB_SHA_7 }}.apk
